In [1]:
import numpy as np

## 3. [1,2,3,4]

In [2]:
arr3 = np.array([1,2,3,4])

In [4]:
print(arr3)
print(type(arr3))

[1 2 3 4]
<class 'numpy.ndarray'>


## 4. 3x4 1s array, 4x3 0s array

In [7]:
arr4ones = np.ones(shape=(3,4))

In [11]:
print(arr4ones)
print(arr4ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [9]:
arr4zeros = np.zeros(shape=(4,3))

In [12]:
print(arr4zeros)
print(arr4zeros.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


## 5. A (2,3) and B (3,4)

In [15]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,19]])

In [16]:
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 19]]


In [17]:
# C = np.dot(A, B)
C = A @ B

In [18]:
print(C)
print(C.shape)

[[ 38  44  50  77]
 [ 83  98 113 170]]
(2, 4)


In [19]:
(A @ B) == np.dot(A, B)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## 6. Eigenvectors and values of [[3,1],[1,2]]
nth columns of eigenvectors is the eigenvector for eigenvalue n 

In [20]:
M = np.array([[3,1],[1,2]])

In [21]:
print(M)

[[3 1]
 [1 2]]


In [22]:
evals, evecs = np.linalg.eig(M)

In [23]:
print(f'Eigenvalues: {evals}')

Eigenvalues: [3.61803399 1.38196601]


In [26]:
print(f'Eigenvectors:\n {evecs}')

Eigenvectors:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
